### ISSUE TITLE
tjstod봇 코드 공유좀 해주세요.

### ISSUE THREAD

**Issue by ghost** [vlzi/tjstodbot-help#1]

**Comment by vI-zi** [comment]
tjstod봇에 관심을 가져주셔서 감사합니다. 봇의 소스는 도움말이 깃허브에 있는 것 답지 않게(?) 공개하지 않고 있습니다. 아무래도 소스가 간단하고 플랫폼 특성상 경쟁자분들께서 출처표기 없이 가져가시는 일이 잦기 때뮨입니다. 또한 봇 계정의 비밀번호 등 여러 정보가 하드코딩되어 있어 공개가 어렵습니다.
